from .models import War, Question, Answer, Test


def yui():
    test = Test.objects.get(title="Тест по ВОВ")
    question2 = Question.objects.get(id = 2)
    answer1 = Answer.objects.create(question=question2, text="22 июня 1941 г.")
    answer2 = Answer.objects.create(question=question2, text="10 июля 1941 г.")
    answer3 = Answer.objects.create(question=question2, text="3 июля 1941 г.", is_correct=True)
    answer4 = Answer.objects.create(question=question2, text="14 августа 1941 г.")
    question3 = Question.objects.create(test=test, text="В каком году началась Битва под Сталинградом")
    answer5 = Answer.objects.create(question=question3, text="1941 г.")
    answer6 = Answer.objects.create(question=question3, text="1942 г.", is_correct=True)
    answer7 = Answer.objects.create(question=question3, text="1943 г.")
    answer8 = Answer.objects.create(question=question3, text="1944 г.")
    question4 = Question.objects.create(test=test, text="Когда началась блокада Ленинграда?")
    answer9 = Answer.objects.create(question=question4, text="8 сентября 1941 г.", is_correct=True)
    answer10 = Answer.objects.create(question=question4, text="30 сентября 1941 г.")
    answer11 = Answer.objects.create(question=question4, text="5 декабря 1942 г.")
    answer12 = Answer.objects.create(question=question4, text="2 февраля 1943 г.")
    question5 = Question.objects.create(test=test, text="Освобождение Ленинграда от вражеской блокады произошло…")
    answer13 = Answer.objects.create(question=question5, text="5 июля 1943 г.")
    answer14 = Answer.objects.create(question=question5, text="8 мая 1945 г.")
    answer15 = Answer.objects.create(question=question5, text="27 января 1944 г.", is_correct=True)
    answer16 = Answer.objects.create(question=question5, text="2 февраля 1943 г.")
    question6 = Question.objects.create(test=test, text="Создание Центрального Штаба партизанского движения произошло…")
    answer17 = Answer.objects.create(question=question6, text="30 мая 1942 г.", is_correct=True)
    answer18 = Answer.objects.create(question=question6, text="22 июня 1941 г.")
    answer19 = Answer.objects.create(question=question6, text="5 июля 1943 г.")
    answer20 = Answer.objects.create(question=question6, text="1 января 1941 г.")
    question7 = Question.objects.create(test=test, text="Какое событие произошло 17 января 1945 г.?")
    answer21 = Answer.objects.create(question=question7, text="Освобождение столицы Латвии Риги")
    answer22 = Answer.objects.create(question=question7, text="Курская битва")
    answer23 = Answer.objects.create(question=question7, text="Нападение Германии на СССР")
    answer24 = Answer.objects.create(question=question7, text="Освобождение столицы Польши Варшавы", is_correct=True)
    question8 = Question.objects.create(test=test, text="Какое событие произошло 9 мая 1945 г.?")
    answer25 = Answer.objects.create(question=question8, text="День Победы", is_correct=True)
    answer26 = Answer.objects.create(question=question8, text="Освобождение Ленинграда от фашисткой блокады")
    answer27 = Answer.objects.create(question=question8, text="Подписание акта о безоговорочной капитуляции Германии")
    answer28 = Answer.objects.create(question=question8, text="Крымская наступательная операция")
    question9 = Question.objects.create(test=test, text="Сколько дней длилась блокада Ленинграда??")
    answer29 = Answer.objects.create(question=question9, text="647 дней")
    answer30 = Answer.objects.create(question=question9, text="780 дней")
    answer31 = Answer.objects.create(question=question9, text="314 дней")
    answer32 = Answer.objects.create(question=question9, text="872 дня", is_correct=True)
    question10 = Question.objects.create(test=test, text="В каком году прошло Смоленское сражение?")
    answer33 = Answer.objects.create(question=question10, text="1941 г.", is_correct=True)
    answer34 = Answer.objects.create(question=question10, text="1942 г.")
    answer35 = Answer.objects.create(question=question10, text="1943 г.")
    answer36 = Answer.objects.create(question=question10, text="1944 г.")


def question_2():
    test = Test.objects.get(title="Тест по ВОВ")
    question11 = Question.objects.create(test=test, text="Сколько городов получило звание «Город-герой»?")
    answer37 = Answer.objects.create(question=question11, text="14")
    answer38 = Answer.objects.create(question=question11, text="15")
    answer39 = Answer.objects.create(question=question11, text="12", is_correct=True)
    answer40 = Answer.objects.create(question=question11, text="11")
    question12 = Question.objects.create(test=test, text="Какой город не является городом-героем?")
    answer41 = Answer.objects.create(question=question12, text="Калининград", is_correct=True)
    answer42 = Answer.objects.create(question=question12, text="Ленинград")
    answer43 = Answer.objects.create(question=question12, text="Керчь")
    answer44 = Answer.objects.create(question=question12, text="Севастополь")
    question13 = Question.objects.create(test=test, text="Сколько месяцев длилась  битва за Москву?")
    answer45 = Answer.objects.create(question=question13, text="5 месяцев")
    answer46 = Answer.objects.create(question=question13, text="7 месяцев", is_correct=True)
    answer47 = Answer.objects.create(question=question13, text="3 месяца")
    answer48 = Answer.objects.create(question=question13, text="4 месяца")