# Generated by Django 5.1.6 on 2025-04-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='war',
            old_name='title',
            new_name='month',
        ),
        migrations.AddField(
            model_name='war',
            name='year',
            field=models.TextField(blank=True),
        ),
    ]
