# Generated by Django 5.1.6 on 2025-04-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_test_alter_question_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='war',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
